title:   Carmine Di Benedetto
logo: "/images/Profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I have more than a decade of experience uncovering actionable insights, telling compelling stories, and giving recommendations to clients on how to increase customer loyalty, advocacy and sales.
  <br><br>
  For over 10 years, I worked as a Senior Manager/Analyst of Business Insights for InMoment – a leader in Customer Experience Management – where I delivered insights for some of the world’s largest brands. It was in this role where I developed a passion for telling a story with data and learned how to present insights in a way that is visually appealing and intuitive. Having to produce 80 reports per year and address each client’s unique business needs was challenging, but I learned how to find solutions that were efficient and satisfied all key stakeholders. I’m looking to apply this knowledge and deliver innovative solutions for a company in need of an Insights Analyst/Manager. 
  <br><br>
  <a href="https://www.linkedin.com/in/carmine-di-benedetto/">View My LinkedIn Profile</a>
  <br><br>
  <a href="https://public.tableau.com/app/profile/cj3204/">View My Tableau Work Samples</a>
  <br><br>
  <a href="https://www.notion.so/carmine-di-benedetto/About-Me-Carmine-Di-Benedetto-4b4d18f1085d4e84afeffb45f845a6f0">View My Notion Portfolios</a>
  
theme: jekyll-theme-minimal
 
